2018-07-14 14:19:42
[SERVER] Socket created
[SERVER] Socket bind complete
[SERVER] Socket now listening 127.0.0.1:12345
[SERVER] Accepting connection from 127.0.0.1:39142
[SERVER] Server Thread started
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "GameOfLife/server.py", line 136, in client_thread
    input_from_client_bytes = Helper.receive_complete_bytestream(conn, MESSAGE_SIZE, MAX_BUFFER_SIZE)
  File "/SEAL/GameOfLife/helper.py", line 30, in receive_complete_bytestream
    current_input_size = sys.getsizeof(current_input)
NameError: name 'sys' is not defined

